# Generated by Django 5.1.2 on 2024-10-29 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('sezione', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Scuola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classi', models.ManyToManyField(related_name='materie', to='rec.classe')),
                ('utenti', models.ManyToManyField(related_name='materie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insegnante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insegnante_profile', to=settings.AUTH_USER_MODEL)),
                ('materie', models.ManyToManyField(related_name='insegnanti', to='rec.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Orario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giornoSettimana', models.CharField(max_length=10)),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orari', to='rec.classe')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orari', to='rec.materia')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='scuola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classi', to='rec.scuola'),
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studenti', to='rec.classe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studente_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('presente', 'Presente'), ('assente', 'Assente')], max_length=10)),
                ('entrata_ritardo', models.TimeField(blank=True, null=True)),
                ('uscita_anticipata', models.TimeField(blank=True, null=True)),
                ('giustificazione', models.BooleanField(default=False)),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenze', to='rec.studente')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scritto', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('orale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voti', to='rec.materia')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voti', to='rec.studente')),
            ],
        ),
    ]
