# Generated by Django 5.1.2 on 2024-10-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezione', models.CharField(max_length=1)),
                ('anno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Insegnante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('ruolo', models.CharField(default='insegnante', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scuola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('indirizzo', models.CharField(max_length=255)),
                ('comprensivo_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('argomenti_trattati', models.TextField(blank=True)),
                ('compiti', models.TextField(blank=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.classe')),
                ('insegnante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.insegnante')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_materia', models.CharField(max_length=100)),
                ('classi', models.ManyToManyField(to='rec.classe')),
                ('insegnante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materie_insegnate', to='rec.insegnante')),
            ],
        ),
        migrations.CreateModel(
            name='OrarioLezioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.CharField(max_length=20)),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.classe')),
                ('insegnante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.insegnante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.materia')),
            ],
        ),
        migrations.AddField(
            model_name='insegnante',
            name='scuola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.scuola'),
        ),
        migrations.AddField(
            model_name='classe',
            name='scuola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.scuola'),
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('ruolo', models.CharField(default='studente', max_length=50)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Presenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('stato', models.CharField(max_length=20)),
                ('orario_entrata', models.TimeField(blank=True, null=True)),
                ('orario_uscita', models.TimeField(blank=True, null=True)),
                ('giustificazione_confermata', models.BooleanField(default=False)),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.studente')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scritto', models.FloatField(blank=True, null=True)),
                ('orale', models.FloatField(blank=True, null=True)),
                ('data', models.DateField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.materia')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.studente')),
            ],
        ),
    ]
