# Generated by Django 5.1.2 on 2024-10-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scuola',
            name='comprensivo_id',
        ),
    ]
