# Generated by Django 5.1.2 on 2024-10-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0002_remove_scuola_comprensivo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='classi',
        ),
    ]
