# Generated by Django 5.1.2 on 2024-11-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0002_insegnante_classi_insegnate_alter_materia_utenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='appunti',
            field=models.TextField(blank=True, null=True),
        ),
    ]
