# Generated by Django 5.1.2 on 2024-11-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0003_voto_appunti'),
    ]

    operations = [
        migrations.AddField(
            model_name='orario',
            name='ultimo_aggiornamento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
