# Generated by Django 5.1.2 on 2024-12-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0004_orario_ultimo_aggiornamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenza',
            options={'ordering': ['-data', 'studente'], 'verbose_name_plural': 'Presenze'},
        ),
    ]
